import ParallelRoutes from "@/components/ParallelRoutes";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Dashboard",
	description: "Generated by create next app",
};

export default function DashboardLayout({
	children,
	users,
	posts,
}: {
	children: React.ReactNode;
	users: React.ReactNode;
	posts: React.ReactNode;
}) {
	return (
		<main className="max-w-[1280px] mx-auto">
			{children}
			<ParallelRoutes users={users} posts={posts} />
		</main>
	);
}
